=== kduvekot/ubl-json/zWMqu/json/schemas/maindoc/CreditNote-2.5.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "urn:oasis:names:specification:ubl:schema:json:CreditNote-2",
  "description": "A document used to specify credits due to the Debtor from the Creditor.",
  "type": "object",
  "properties": {
    "$jsonschema": {
      "const": "urn:oasis:names:specification:ubl:schema:json:CreditNote-2",
      "description": "Identifies the JSON schema governing this instance."
    },
    "UBLExtensions": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonExtensionComponents-2#/$defs/UBLExtensionsType"
    },
    "Signature": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/SignatureType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/SignatureType"
          }
        }
      ]
    },
    "UBLVersionID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/UBLVersionID"
    },
    "CustomizationID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/CustomizationID"
    },
    "ProfileID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ProfileID"
    },
    "ProfileExecutionID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ProfileExecutionID"
    },
    "ID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ID"
    },
    "CopyIndicator": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/CopyIndicator"
    },
    "UUID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/UUID"
    },
    "IssueDate": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/IssueDate"
    },
    "IssueTime": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/IssueTime"
    },
    "DueDate": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/DueDate"
    },
    "TaxPointDate": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/TaxPointDate"
    },
    "CreditNoteTypeCode": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/CreditNoteTypeCode"
    },
    "Note": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/Note"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/Note"
          }
        }
      ]
    },
    "DocumentCurrencyCode": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/DocumentCurrencyCode"
    },
    "TaxCurrencyCode": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/TaxCurrencyCode"
    },
    "PricingCurrencyCode": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/PricingCurrencyCode"
    },
    "PaymentCurrencyCode": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/PaymentCurrencyCode"
    },
    "PaymentAlternativeCurrencyCode": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/PaymentAlternativeCurrencyCode"
    },
    "AccountingCostCode": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/AccountingCostCode"
    },
    "AccountingCost": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/AccountingCost"
    },
    "LineCountNumeric": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/LineCountNumeric"
    },
    "BuyerReference": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/BuyerReference"
    },
    "DefaultLanguageCode": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/DefaultLanguageCode"
    },
    "InvoicePeriod": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PeriodType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PeriodType"
          }
        }
      ]
    },
    "DiscrepancyResponse": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/ResponseType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/ResponseType"
          }
        }
      ]
    },
    "OrderReference": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/OrderReferenceType"
    },
    "BillingReference": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/BillingReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/BillingReferenceType"
          }
        }
      ]
    },
    "DespatchDocumentReference": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
          }
        }
      ]
    },
    "DeliveryNoteDocumentReference": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
          }
        }
      ]
    },
    "WorkReportDocumentReference": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
          }
        }
      ]
    },
    "ReceiptDocumentReference": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
          }
        }
      ]
    },
    "ContractDocumentReference": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
          }
        }
      ]
    },
    "AdditionalDocumentReference": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
          }
        }
      ]
    },
    "StatementDocumentReference": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
          }
        }
      ]
    },
    "OriginatorDocumentReference": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
          }
        }
      ]
    },
    "ProjectReference": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/ProjectReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/ProjectReferenceType"
          }
        }
      ]
    },
    "BuyerAssignedReference": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/BuyerAssignedReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/BuyerAssignedReferenceType"
          }
        }
      ]
    },
    "PurchaseReference": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PurchaseReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PurchaseReferenceType"
          }
        }
      ]
    },
    "Annotation": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/AnnotationType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/AnnotationType"
          }
        }
      ]
    },
    "AccountingSupplierParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/SupplierPartyType"
    },
    "AccountingCustomerParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/CustomerPartyType"
    },
    "PayeeParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
    },
    "BuyerCustomerParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/CustomerPartyType"
    },
    "SellerSupplierParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/SupplierPartyType"
    },
    "TaxRepresentativeParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
    },
    "Delivery": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DeliveryType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DeliveryType"
          }
        }
      ]
    },
    "DeliveryTerms": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DeliveryTermsType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DeliveryTermsType"
          }
        }
      ]
    },
    "PaymentMeans": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PaymentMeansType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PaymentMeansType"
          }
        }
      ]
    },
    "PaymentTerms": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PaymentTermsType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PaymentTermsType"
          }
        }
      ]
    },
    "TaxExchangeRate": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/ExchangeRateType"
    },
    "PricingExchangeRate": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/ExchangeRateType"
    },
    "PaymentExchangeRate": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/ExchangeRateType"
    },
    "PaymentAlternativeExchangeRate": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/ExchangeRateType"
    },
    "AllowanceCharge": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/AllowanceChargeType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/AllowanceChargeType"
          }
        }
      ]
    },
    "TaxTotal": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/TaxTotalType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/TaxTotalType"
          }
        }
      ]
    },
    "WithholdingTaxTotal": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/TaxTotalType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/TaxTotalType"
          }
        }
      ]
    },
    "LegalMonetaryTotal": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/MonetaryTotalType"
    },
    "CollectionCreditNoteLine": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/CreditNoteLineType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/CreditNoteLineType"
          }
        }
      ]
    },
    "CreditNoteLine": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/CreditNoteLineType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/CreditNoteLineType"
          },
          "minItems": 1
        }
      ]
    }
  },
  "required": [
    "$jsonschema",
    "ID",
    "IssueDate",
    "AccountingSupplierParty",
    "LegalMonetaryTotal",
    "CreditNoteLine"
  ],
  "additionalProperties": false,
  "minProperties": 1,
  "title": "Credit Note. Details"
}

=== kduvekot/ubl-json/zWMqu/json/examples/UBL-CreditNote-2.0-Example.json
{
  "$jsonschema": "urn:oasis:names:specification:ubl:schema:json:CreditNote-2",
  "UBLVersionID": "2.0",
  "CustomizationID": "urn:oasis:names:specification:ubl:xpath:CreditNote-2.0:sbs-1.0-draft",
  "ProfileID": "bpid:urn:oasis:names:draft:bpss:ubl-2-sbs-credit-notification-draft",
  "ID": "CN758494",
  "CopyIndicator": false,
  "UUID": "349ABBAE-DF9D-40B4-849F-94C5FF9D1AF4",
  "IssueDate": "2005-06-25",
  "TaxPointDate": "2005-06-21",
  "Note": "sample",
  "AccountingSupplierParty": {
    "CustomerAssignedAccountID": "CO001",
    "Party": {
      "PartyName": {
        "Name": "Consortial"
      },
      "PostalAddress": {
        "StreetName": "Busy Street",
        "BuildingName": "Thereabouts",
        "BuildingNumber": "56A",
        "CityName": "Farthing",
        "PostalZone": "AA99 1BB",
        "CountrySubentity": "Heremouthshire",
        "AddressLine": {
          "Line": "The Roundabout"
        },
        "Country": {
          "IdentificationCode": "GB"
        }
      },
      "PartyTaxScheme": {
        "RegistrationName": "Farthing Purchasing Consortium",
        "CompanyID": "175 269 2355",
        "ExemptionReason": "N/A",
        "TaxScheme": {
          "ID": "VAT",
          "TaxTypeCode": "VAT"
        }
      },
      "Contact": {
        "Name": "Mrs Bouquet",
        "Telephone": "0158 1233714",
        "Telefax": "0158 1233856",
        "ElectronicMail": "bouquet@fpconsortial.co.uk"
      }
    }
  },
  "AccountingCustomerParty": {
    "CustomerAssignedAccountID": "XFB01",
    "SupplierAssignedAccountID": "GT00978567",
    "Party": {
      "PartyName": {
        "Name": "IYT Corporation"
      },
      "PostalAddress": {
        "StreetName": "Avon Way",
        "BuildingName": "Thereabouts",
        "BuildingNumber": "56A",
        "CityName": "Bridgtow",
        "PostalZone": "ZZ99 1ZZ",
        "CountrySubentity": "Avon",
        "AddressLine": {
          "Line": "3rd Floor, Room 5"
        },
        "Country": {
          "IdentificationCode": "GB"
        }
      },
      "PartyTaxScheme": {
        "RegistrationName": "Bridgtow District Council",
        "CompanyID": "12356478",
        "ExemptionReason": "Local Authority",
        "TaxScheme": {
          "ID": "UK VAT",
          "TaxTypeCode": "VAT"
        }
      },
      "Contact": {
        "Name": "Mr Fred Churchill",
        "Telephone": "0127 2653214",
        "Telefax": "0127 2653215",
        "ElectronicMail": "fred@iytcorporation.gov.uk"
      }
    }
  },
  "TaxTotal": {
    "TaxAmount": {
      "value": 17.5,
      "currencyID": "GBP"
    },
    "TaxEvidenceIndicator": true,
    "TaxSubtotal": {
      "TaxableAmount": {
        "value": 100.0,
        "currencyID": "GBP"
      },
      "TaxAmount": {
        "value": 17.5,
        "currencyID": "GBP"
      },
      "TaxCategory": {
        "ID": "A",
        "TaxScheme": {
          "ID": "UK VAT",
          "TaxTypeCode": "VAT"
        }
      }
    }
  },
  "LegalMonetaryTotal": {
    "LineExtensionAmount": {
      "value": 100.0,
      "currencyID": "GBP"
    },
    "TaxExclusiveAmount": {
      "value": 90.0,
      "currencyID": "GBP"
    },
    "PayableAmount": {
      "value": 107.5,
      "currencyID": "GBP"
    }
  },
  "CreditNoteLine": {
    "ID": "1",
    "Note": "as agreed on phone, the invoice should have been cancelled earlier, apologies",
    "CreditedQuantity": {
      "value": 100,
      "unitCode": "KGM"
    },
    "LineExtensionAmount": {
      "value": 100.0,
      "currencyID": "GBP"
    },
    "TaxPointDate": "2005-06-21",
    "DiscrepancyResponse": {
      "ReferenceID": "A00095678",
      "Description": "invoice cancelation"
    },
    "BillingReference": {
      "InvoiceDocumentReference": {
        "ID": "A00095678",
        "UUID": "849FBBCE-E081-40B4-906C-94C5FF9D1AC3",
        "IssueDate": "2005-06-21"
      }
    },
    "TaxTotal": {
      "TaxAmount": {
        "value": 17.5,
        "currencyID": "GBP"
      },
      "TaxEvidenceIndicator": true,
      "TaxSubtotal": {
        "TaxableAmount": {
          "value": 100.0,
          "currencyID": "GBP"
        },
        "TaxAmount": {
          "value": 17.5,
          "currencyID": "GBP"
        },
        "TaxCategory": {
          "ID": "A",
          "TaxScheme": {
            "ID": "UK VAT",
            "TaxTypeCode": "VAT"
          }
        }
      }
    },
    "Item": {
      "Description": "Acme beeswax",
      "Name": "beeswax",
      "BuyersItemIdentification": {
        "ID": "6578489"
      },
      "SellersItemIdentification": {
        "ID": "17589683"
      },
      "ItemInstance": {
        "LotIdentification": {
          "LotNumberID": "546378239",
          "ExpiryDate": "2010-01-01"
        }
      }
    },
    "Price": {
      "PriceAmount": {
        "value": 1.0,
        "currencyID": "GBP"
      },
      "BaseQuantity": {
        "value": 1,
        "unitCode": "KGM"
      }
    }
  }
}
