=== kduvekot/ubl-json/zWMqu/json/schemas/maindoc/GoodsItemPassport-2.5.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "urn:oasis:names:specification:ubl:schema:json:GoodsItemPassport-2",
  "description": "A document providing a temporary export license, also knowned as an ATA Carnet",
  "type": "object",
  "properties": {
    "$jsonschema": {
      "const": "urn:oasis:names:specification:ubl:schema:json:GoodsItemPassport-2",
      "description": "Identifies the JSON schema governing this instance."
    },
    "UBLExtensions": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonExtensionComponents-2#/$defs/UBLExtensionsType"
    },
    "Signature": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/SignatureType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/SignatureType"
          }
        }
      ]
    },
    "UBLVersionID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/UBLVersionID"
    },
    "CustomizationID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/CustomizationID"
    },
    "ProfileID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ProfileID"
    },
    "ProfileExecutionID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ProfileExecutionID"
    },
    "ID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ID"
    },
    "UUID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/UUID"
    },
    "IssueDate": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/IssueDate"
    },
    "IssueTime": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/IssueTime"
    },
    "StatusCode": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/StatusCode"
    },
    "Status": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/Status"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/Status"
          }
        }
      ]
    },
    "Note": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/Note"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/Note"
          }
        }
      ]
    },
    "VersionID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/VersionID"
    },
    "ExportReasonCode": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ExportReasonCode"
    },
    "ExportReason": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ExportReason"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ExportReason"
          }
        }
      ]
    },
    "ValidityPeriod": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PeriodType"
    },
    "IssuerParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
    },
    "HolderParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
    },
    "RepresentativeParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
    },
    "ExportingGuarantorParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
    },
    "ImportingGuarantorParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
    },
    "ExportingCustomsParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
    },
    "ImportingCustomsParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
    },
    "Shipment": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/ShipmentType"
    },
    "GoodsItemPassportCounterfoil": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/GoodsItemPassportCounterfoilType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/GoodsItemPassportCounterfoilType"
          },
          "minItems": 1
        }
      ]
    },
    "IssuerEndorsement": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/EndorsementType"
    },
    "AdditionalDocumentReference": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
          }
        }
      ]
    },
    "DocumentDistribution": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentDistributionType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentDistributionType"
          }
        }
      ]
    }
  },
  "required": [
    "$jsonschema",
    "ID",
    "HolderParty",
    "Shipment",
    "GoodsItemPassportCounterfoil"
  ],
  "additionalProperties": false,
  "minProperties": 1,
  "title": "Goods Item Passport. Details"
}

=== kduvekot/ubl-json/zWMqu/json/examples/UBL-GoodsItemPassport-2.3-Example-Issued.json
{
  "$jsonschema": "urn:oasis:names:specification:ubl:schema:json:GoodsItemPassport-2",
  "CustomizationID": "UBL-2.3",
  "ID": "ata01661",
  "IssueDate": "2019-02-21",
  "StatusCode": "ISSUED",
  "ValidityPeriod": {
    "StartDate": "2019-02-21",
    "EndDate": "2020-02-20"
  },
  "IssuerParty": {
    "PartyName": {
      "Name": "Dansk Industri"
    },
    "PostalAddress": {
      "ID": "6916",
      "StreetName": "Vesterbrogade 1L, 1.sal",
      "CityName": "København V.",
      "PostalZone": "1620",
      "Country": {
        "IdentificationCode": "DK",
        "Name": "Denmark"
      }
    },
    "PartyLegalEntity": {
      "CompanyID": "16077593"
    }
  },
  "HolderParty": {
    "PartyName": {
      "Name": "STEFCO A/S"
    },
    "PostalAddress": {
      "StreetName": "Industrivej 3",
      "CityName": "Ørum Djurs",
      "PostalZone": "8586",
      "Country": {
        "IdentificationCode": "DK",
        "Name": "Denmark"
      }
    },
    "PartyLegalEntity": {
      "CompanyID": "DK89343487"
    },
    "Contact": {
      "Name": "Andreas Andersen"
    }
  },
  "RepresentativeParty": {
    "PartyName": {
      "Name": "Grenå Tools"
    },
    "PostalAddress": {
      "StreetName": "Højdevej 18",
      "CityName": "Grenå",
      "PostalZone": "8500",
      "Country": {
        "IdentificationCode": "DK",
        "Name": "Denmark"
      }
    },
    "Person": {
      "FirstName": "Kirsten",
      "FamilyName": "Jensen",
      "IdentityDocumentReference": {
        "ID": {
          "value": "325334535",
          "schemeID": "Passport"
        }
      }
    }
  },
  "ExportingGuarantorParty": {
    "PartyName": {
      "Name": "Dansk Erhverv"
    },
    "PostalAddress": {
      "StreetName": "Slotsholmsgade",
      "BuildingNumber": "1",
      "CityName": "København K",
      "PostalZone": "1216",
      "Country": {
        "IdentificationCode": "DK"
      }
    },
    "PartyLegalEntity": {
      "CompanyID": "43232010"
    }
  },
  "Shipment": {
    "ID": "32453",
    "DeclaredStatisticsValueAmount": {
      "value": 34800.0,
      "currencyID": "DKK"
    },
    "Consignment": {
      "ID": "1",
      "TotalInvoiceAmount": {
        "value": 44250.0,
        "currencyID": "DKK"
      },
      "GrossWeightMeasure": {
        "value": 230.8,
        "unitCode": "KGM"
      },
      "Information": "Professional equipment",
      "TotalGoodsItemQuantity": 23,
      "FinalDestinationCountry": {
        "IdentificationCode": "CH"
      },
      "TransitCountry": {
        "IdentificationCode": "DE"
      },
      "FirstArrivalPortLocation": {
        "Name": "Padborg"
      },
      "LastExitPortLocation": {
        "Name": "Bietingen"
      }
    },
    "GoodsItem": [
      {
        "ID": "1",
        "DeclaredCustomsValueAmount": {
          "value": 0.0,
          "currencyID": "DKK"
        },
        "DeclaredStatisticsValueAmount": {
          "value": 4500.0,
          "currencyID": "DKK"
        },
        "Quantity": {
          "value": 2,
          "unitCode": "H87"
        },
        "Item": {
          "Description": "HILTI TE2 + TE35 Boremaskiner",
          "OriginCountry": {
            "IdentificationCode": "DE"
          },
          "AdditionalItemProperty": [
            {
              "Name": "AlcoholPercentage",
              "Value": "0"
            },
            {
              "Name": "DegreeOfPlato",
              "Value": "0"
            }
          ]
        }
      },
      {
        "ID": "2",
        "DeclaredCustomsValueAmount": {
          "value": 0.0,
          "currencyID": "DKK"
        },
        "DeclaredStatisticsValueAmount": {
          "value": 500.0,
          "currencyID": "DKK"
        },
        "Quantity": {
          "value": 1,
          "unitCode": "H87"
        },
        "Item": {
          "Description": "BACHO S910, Topnøglesæt",
          "OriginCountry": {
            "IdentificationCode": "DE"
          }
        }
      },
      {
        "ID": "3",
        "DeclaredCustomsValueAmount": {
          "value": 0.0,
          "currencyID": "DKK"
        },
        "DeclaredStatisticsValueAmount": {
          "value": 1500.0,
          "currencyID": "DKK"
        },
        "Quantity": {
          "value": 1,
          "unitCode": "H87"
        },
        "Item": {
          "Description": "DEWALT DC822, Boltspænder",
          "OriginCountry": {
            "IdentificationCode": "US"
          }
        }
      },
      {
        "ID": "4",
        "DeclaredCustomsValueAmount": {
          "value": 1500.0,
          "currencyID": "DKK"
        },
        "DeclaredStatisticsValueAmount": {
          "value": 1500.0,
          "currencyID": "DKK"
        },
        "Quantity": {
          "value": 1,
          "unitCode": "H87"
        },
        "Item": {
          "Description": "DEWALT DC542, Fugepistol",
          "OriginCountry": {
            "IdentificationCode": "US"
          }
        }
      },
      {
        "ID": "5",
        "DeclaredStatisticsValueAmount": {
          "value": 1000.0,
          "currencyID": "DKK"
        },
        "Quantity": {
          "value": 1,
          "unitCode": "H87"
        },
        "Item": {
          "Description": "METABO GE700, Pinolsliber",
          "OriginCountry": {
            "IdentificationCode": "DE"
          }
        }
      },
      {
        "ID": "6",
        "DeclaredCustomsValueAmount": {
          "value": 1000.0,
          "currencyID": "DKK"
        },
        "DeclaredStatisticsValueAmount": {
          "value": 1000.0,
          "currencyID": "DKK"
        },
        "Quantity": {
          "value": 1,
          "unitCode": "H87"
        },
        "Item": {
          "Description": "METABO SBE 1010, Boremaskine",
          "OriginCountry": {
            "IdentificationCode": "DE"
          }
        }
      },
      {
        "ID": "7",
        "DeclaredCustomsValueAmount": {
          "value": 2500.0,
          "currencyID": "DKK"
        },
        "DeclaredStatisticsValueAmount": {
          "value": 2500.0,
          "currencyID": "DKK"
        },
        "Quantity": {
          "value": 1,
          "unitCode": "H87"
        },
        "Item": {
          "Description": "KAMA AD 105S, Båndsav",
          "OriginCountry": {
            "IdentificationCode": "US"
          }
        }
      },
      {
        "ID": "8",
        "DeclaredCustomsValueAmount": {
          "value": 2500.0,
          "currencyID": "DKK"
        },
        "DeclaredStatisticsValueAmount": {
          "value": 2500.0,
          "currencyID": "DKK"
        },
        "Quantity": {
          "value": 1,
          "unitCode": "H87"
        },
        "Item": {
          "Description": "LIFTKET 021/51, Talje",
          "OriginCountry": {
            "IdentificationCode": "DE"
          }
        }
      },
      {
        "ID": "9",
        "DeclaredCustomsValueAmount": {
          "value": 500.0,
          "currencyID": "DKK"
        },
        "DeclaredStatisticsValueAmount": {
          "value": 500.0,
          "currencyID": "DKK"
        },
        "Quantity": {
          "value": 1,
          "unitCode": "H87"
        },
        "Item": {
          "Description": "KING TONY 6316, Topnøglesæt",
          "OriginCountry": {
            "IdentificationCode": "US"
          }
        }
      },
      {
        "ID": "10",
        "DeclaredCustomsValueAmount": {
          "value": 1000.0,
          "currencyID": "DKK"
        },
        "DeclaredStatisticsValueAmount": {
          "value": 1000.0,
          "currencyID": "DKK"
        },
        "Quantity": {
          "value": 2,
          "unitCode": "H87"
        },
        "Item": {
          "Description": "STAHL WILLE 730/02, Momentnøgle",
          "OriginCountry": {
            "IdentificationCode": "DE"
          }
        }
      },
      {
        "ID": "11",
        "DeclaredCustomsValueAmount": {
          "value": 500.0,
          "currencyID": "DKK"
        },
        "DeclaredStatisticsValueAmount": {
          "value": 500.0,
          "currencyID": "DKK"
        },
        "Quantity": {
          "value": 1,
          "unitCode": "H87"
        },
        "Item": {
          "Description": "HADEF 750kg, Talje",
          "OriginCountry": {
            "IdentificationCode": "DE"
          }
        }
      },
      {
        "ID": "12",
        "DeclaredCustomsValueAmount": {
          "value": 750.0,
          "currencyID": "DKK"
        },
        "DeclaredStatisticsValueAmount": {
          "value": 750.0,
          "currencyID": "DKK"
        },
        "Quantity": {
          "value": 2,
          "unitCode": "H87"
        },
        "Item": {
          "Description": "HADEF 250kg, Talje",
          "OriginCountry": {
            "IdentificationCode": "DE"
          }
        }
      },
      {
        "ID": "13",
        "DeclaredCustomsValueAmount": {
          "value": 1500.0,
          "currencyID": "DKK"
        },
        "DeclaredStatisticsValueAmount": {
          "value": 1500.0,
          "currencyID": "DKK"
        },
        "Quantity": {
          "value": 1,
          "unitCode": "H87"
        },
        "Item": {
          "Description": "DURA PRO 2000kg, Dunkraft",
          "OriginCountry": {
            "IdentificationCode": "DE"
          }
        }
      },
      {
        "ID": "14",
        "DeclaredCustomsValueAmount": {
          "value": 2000.0,
          "currencyID": "DKK"
        },
        "DeclaredStatisticsValueAmount": {
          "value": 2000.0,
          "currencyID": "DKK"
        },
        "Quantity": {
          "value": 1,
          "unitCode": "H87"
        },
        "Item": {
          "Description": "BY45A, Donkraft",
          "OriginCountry": {
            "IdentificationCode": "DE"
          }
        }
      },
      {
        "ID": "15",
        "DeclaredCustomsValueAmount": {
          "value": 1500.0,
          "currencyID": "DKK"
        },
