=== kduvekot/ubl-json/zWMqu/json/schemas/maindoc/ProductActivity-2.5.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "urn:oasis:names:specification:ubl:schema:json:ProductActivity-2",
  "description": "A document reporting the movement of goods at specified retail locations for inventory tracking purposes.",
  "type": "object",
  "properties": {
    "$jsonschema": {
      "const": "urn:oasis:names:specification:ubl:schema:json:ProductActivity-2",
      "description": "Identifies the JSON schema governing this instance."
    },
    "UBLExtensions": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonExtensionComponents-2#/$defs/UBLExtensionsType"
    },
    "Signature": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/SignatureType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/SignatureType"
          }
        }
      ]
    },
    "UBLVersionID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/UBLVersionID"
    },
    "CustomizationID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/CustomizationID"
    },
    "ProfileID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ProfileID"
    },
    "ProfileExecutionID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ProfileExecutionID"
    },
    "ID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ID"
    },
    "CopyIndicator": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/CopyIndicator"
    },
    "UUID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/UUID"
    },
    "IssueDate": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/IssueDate"
    },
    "IssueTime": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/IssueTime"
    },
    "Note": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/Note"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/Note"
          }
        }
      ]
    },
    "DocumentCurrencyCode": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/DocumentCurrencyCode"
    },
    "ActivityPeriod": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PeriodType"
    },
    "DocumentReference": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
          }
        }
      ]
    },
    "SenderParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
    },
    "ReceiverParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
    },
    "SupplyChainActivityDataLine": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/ActivityDataLineType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/ActivityDataLineType"
          },
          "minItems": 1
        }
      ]
    }
  },
  "required": [
    "$jsonschema",
    "ID",
    "IssueDate",
    "ActivityPeriod",
    "SenderParty",
    "ReceiverParty",
    "SupplyChainActivityDataLine"
  ],
  "additionalProperties": false,
  "minProperties": 1,
  "title": "Product Activity. Details"
}

=== kduvekot/ubl-json/zWMqu/json/examples/UBL-ProductActivity-2.1-Example-1.json
{
  "$jsonschema": "urn:oasis:names:specification:ubl:schema:json:ProductActivity-2",
  "UBLVersionID": "2.1",
  "ProfileID": "bpid:urn:oasis:names:draft:bpss:ubl-2-1-cpfr-product-activity-draft",
  "ID": "PA_758494",
  "CopyIndicator": false,
  "UUID": "349ABBAE-DF9D-40B4-849F-94C5FF9D1AF4",
  "IssueDate": "2005-01-10",
  "IssueTime": "12:00:01.000Z",
  "Note": "sample Document",
  "ActivityPeriod": {
    "StartDate": "2005-02-26",
    "EndDate": "2005-12-26"
  },
  "SenderParty": {
    "PartyIdentification": {
      "ID": "6903148000007"
    },
    "PartyName": {
      "Name": "Consortial"
    },
    "PostalAddress": {
      "StreetName": "Busy Street",
      "BuildingName": "Thereabouts",
      "BuildingNumber": "56A",
      "CityName": "Farthing",
      "PostalZone": "AA99 1BB",
      "CountrySubentity": "Heremouthshire",
      "AddressLine": {
        "Line": "The Roundabout"
      },
      "Country": {
        "IdentificationCode": "GB"
      }
    },
    "PartyTaxScheme": {
      "RegistrationName": "Farthing Purchasing Consortium",
      "CompanyID": "175 269 2355",
      "ExemptionReason": "N/A",
      "TaxScheme": {
        "ID": "VAT",
        "TaxTypeCode": "VAT"
      }
    },
    "Contact": {
      "Name": "Mrs Bouquet",
      "Telephone": "0158 1233714",
      "Telefax": "0158 1233856",
      "ElectronicMail": "bouquet@fpconsortial.co.uk"
    }
  },
  "ReceiverParty": {
    "PartyIdentification": {
      "ID": "2203148000007"
    },
    "PartyName": {
      "Name": "IYT Corporation"
    },
    "PostalAddress": {
      "StreetName": "Avon Way",
      "BuildingName": "Thereabouts",
      "BuildingNumber": "56A",
      "CityName": "Bridgtow",
      "PostalZone": "ZZ99 1ZZ",
      "CountrySubentity": "Avon",
      "AddressLine": {
        "Line": "3rd Floor, Room 5"
      },
      "Country": {
        "IdentificationCode": "GB"
      }
    },
    "PartyTaxScheme": {
      "RegistrationName": "Bridgtow District Council",
      "CompanyID": "12356478",
      "ExemptionReason": "Local Authority",
      "TaxScheme": {
        "ID": "UK VAT",
        "TaxTypeCode": "VAT"
      }
    },
    "Contact": {
      "Name": "Mr Fred Churchill",
      "Telephone": "0127 2653214",
      "Telefax": "0127 2653215",
      "ElectronicMail": "fred@iytcorporation.gov.uk"
    }
  },
  "SupplyChainActivityDataLine": {
    "ID": "SCADL_SHIPMENT001",
    "SupplyChainActivityTypeCode": "SHIPMENTS",
    "BuyerCustomerParty": {
      "Party": {
        "PartyIdentification": {
          "ID": "2203148000007"
        }
      }
    },
    "SellerSupplierParty": {
      "Party": {
        "PartyIdentification": {
          "ID": "6903148000007"
        }
      }
    },
    "ActivityOriginLocation": {
      "ID": "1234567890"
    },
    "SalesItem": {
      "Quantity": {
        "value": 20,
        "unitCode": "KGM"
      },
      "Item": {
        "StandardItemIdentification": {
          "ID": "06110123456784"
        }
      }
    }
  }
}

=== kduvekot/ubl-json/zWMqu/json/examples/UBL-ProductActivity-2.1-Example-3.json
{
  "$jsonschema": "urn:oasis:names:specification:ubl:schema:json:ProductActivity-2",
  "UBLVersionID": "2.1",
  "ID": "ID0113",
  "CopyIndicator": false,
  "IssueDate": "2010-04-08",
  "Note": "Report about sales of goods in Beta Shop's shops located in Bologna.",
  "ActivityPeriod": {
    "StartDate": "2010-04-07"
  },
  "SenderParty": {
    "PartyName": {
      "Name": "Beta Shop"
    },
    "PostalAddress": {
      "StreetName": "Via Emilia",
      "BuildingNumber": "1",
      "CityName": "Modena",
      "PostalZone": "41121",
      "Country": {
        "IdentificationCode": "IT",
        "Name": "Italy"
      }
    },
    "Contact": {
      "Name": "Mr Delta",
      "Telephone": "0039 059 33000000",
      "Telefax": "0039 059 33000055",
      "ElectronicMail": "delta@betashop.it"
    }
  },
  "ReceiverParty": {
    "PartyName": {
      "Name": "Arancio Forniture spa"
    },
    "PostalAddress": {
      "Floor": "5",
      "Room": "29",
      "StreetName": "Via Dell'Arcoveggio",
      "BuildingNumber": "403",
      "Department": "Marketing Office",
      "CityName": "Bologna",
      "PostalZone": "40129",
      "Country": {
        "IdentificationCode": "IT",
        "Name": "Italy"
      }
    },
    "Contact": {
      "Name": "Mr Rossi",
      "Telephone": "0039 051 23000000",
      "Telefax": "0039 051 23000023",
      "ElectronicMail": "rossi@arancioforniture.it"
    }
  },
  "SupplyChainActivityDataLine": {
    "ID": "1",
    "SupplyChainActivityTypeCode": "SALES",
    "ActivityOriginLocation": {
      "Description": "Shop in the city center",
      "Address": {
        "StreetName": "Via Rizzoli",
        "BuildingNumber": "208",
        "CityName": "Bologna",
        "PostalZone": "40121",
        "Country": {
          "IdentificationCode": "IT",
          "Name": "Italy"
        }
      }
    },
    "SalesItem": [
      {
        "Quantity": {
          "value": 8,
          "unitCode": "NAR"
        },
        "Item": {
          "Description": "shirt",
          "BuyersItemIdentification": {
            "ID": "SH009"
          },
          "SellersItemIdentification": {
            "ID": "DD88"
          }
        }
      },
      {
        "Quantity": {
          "value": 3,
          "unitCode": "NAR"
        },
        "Item": {
          "Description": "trousers",
          "BuyersItemIdentification": {
            "ID": "TH009"
          },
          "SellersItemIdentification": {
            "ID": "DA008"
          }
        }
      }
    ]
  }
}

=== kduvekot/ubl-json/zWMqu/json/examples/UBL-ProductActivity-2.1-Example-2.json
{
  "$jsonschema": "urn:oasis:names:specification:ubl:schema:json:ProductActivity-2",
  "UBLVersionID": "2.1",
  "ID": "ID0009",
  "CopyIndicator": false,
  "IssueDate": "2010-04-10",
  "Note": "Report about movements of goods between Beta Shop's locations located in\n        Emilia-Romagna.",
  "ActivityPeriod": {
    "StartDate": "2010-04-09"
  },
  "SenderParty": {
    "PartyName": {
      "Name": "Beta Shop"
    },
    "PostalAddress": {
      "StreetName": "Via Emilia",
      "BuildingNumber": "1",
      "CityName": "Modena",
      "PostalZone": "41121",
      "Country": {
        "IdentificationCode": "IT",
        "Name": "Italy"
      }
    },
    "Contact": {
      "Name": "Mr Delta",
      "Telephone": "0039 059 33000000",
      "Telefax": "0039 059 33000055",
      "ElectronicMail": "delta@betashop.it"
    }
  },
  "ReceiverParty": {
    "PartyName": {
      "Name": "Arancio Forniture spa"
    },
    "PostalAddress": {
      "StreetName": "Via Dell'Arcoveggio",
      "BuildingNumber": "403",
      "CityName": "Bologna",
      "PostalZone": "40129",
      "Country": {
        "IdentificationCode": "IT",
        "Name": "Italy"
      }
    },
    "Contact": {
      "Name": "Mr Rossi",
      "Telephone": "0039 051 23000000",
      "Telefax": "0039 051 23000023",
      "ElectronicMail": "rossi@arancioforniture.it"
    }
  },
  "SupplyChainActivityDataLine": [
    {
      "ID": "1",
      "SupplyChainActivityTypeCode": "SHIPMENTS",
      "ActivityOriginLocation": {
        "Address": {
          "StreetName": "Via Dell'Arcoveggio",
          "BuildingNumber": "403",
          "CityName": "Bologna",
          "PostalZone": "40129",
          "Country": {
            "IdentificationCode": "IT",
            "Name": "Italy"
          }
        }
      },
      "ActivityFinalLocation": {
        "Description": "Shop in the city center",
        "Address": {
          "StreetName": "Via Rizzoli",
          "BuildingNumber": "208",
          "CityName": "Bologna",
          "PostalZone": "40121",
          "Country": {
            "IdentificationCode": "IT",
            "Name": "Italy"
          }
        }
      },
      "SalesItem": {
        "Quantity": {
          "value": 20,
          "unitCode": "NAR"
        },
        "Item": {
          "Description": "shirt",
          "BuyersItemIdentification": {
            "ID": "SH009"
          },
          "SellersItemIdentification": {
            "ID": "DD88"
          }
        }
      }
    },
    {
      "ID": "2",
      "SupplyChainActivityTypeCode": "SHIPMENTS",
      "ActivityOriginLocation": {
        "Address": {
          "StreetName": "Via Dell'Arcoveggio",
          "BuildingNumber": "403",
          "CityName": "Bologna",
          "PostalZone": "40129",
          "Country": {
            "IdentificationCode": "IT",
            "Name": "Italy"
          }
        }
      },
      "ActivityFinalLocation": {
        "Description": "Store",
        "Address": {
          "StreetName": "Via Delle Fonti",
          "BuildingNumber": "209",
          "CityName": "Bologna",
          "PostalZone": "40128",
          "Country": {
            "IdentificationCode": "IT",
            "Name": "Italy"
          }
        }
      },
      "SalesItem": [
        {
          "Quantity": {
            "value": 200,
            "unitCode": "NAR"
          },
          "Item": {
            "Description": "shirt",
            "BuyersItemIdentification": {
              "ID": "SH009"
            },
            "SellersItemIdentification": {
              "ID": "DD88"
            }
          }
        },
        {
          "Quantity": {
            "value": 150,
            "unitCode": "NAR"
          },
          "Item": {
            "Description": "trousers",
            "BuyersItemIdentification": {
              "ID": "TH009"
            },
            "SellersItemIdentification": {
              "ID": "DA008"
            }
          }
        }
      ]
    }
  ]
}
