=== kduvekot/ubl-json/zWMqu/json/schemas/maindoc/RequestForQuotation-2.5.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "urn:oasis:names:specification:ubl:schema:json:RequestForQuotation-2",
  "description": "A document used to request a Quotation for goods and services from a Seller.",
  "type": "object",
  "properties": {
    "$jsonschema": {
      "const": "urn:oasis:names:specification:ubl:schema:json:RequestForQuotation-2",
      "description": "Identifies the JSON schema governing this instance."
    },
    "UBLExtensions": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonExtensionComponents-2#/$defs/UBLExtensionsType"
    },
    "Signature": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/SignatureType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/SignatureType"
          }
        }
      ]
    },
    "UBLVersionID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/UBLVersionID"
    },
    "CustomizationID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/CustomizationID"
    },
    "ProfileID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ProfileID"
    },
    "ProfileExecutionID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ProfileExecutionID"
    },
    "ID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ID"
    },
    "CopyIndicator": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/CopyIndicator"
    },
    "UUID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/UUID"
    },
    "IssueDate": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/IssueDate"
    },
    "IssueTime": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/IssueTime"
    },
    "SubmissionDueDate": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/SubmissionDueDate"
    },
    "Note": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/Note"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/Note"
          }
        }
      ]
    },
    "PricingCurrencyCode": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/PricingCurrencyCode"
    },
    "LineCountNumeric": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/LineCountNumeric"
    },
    "RequestedValidityPeriod": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PeriodType"
    },
    "CatalogueDocumentReference": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
    },
    "AdditionalDocumentReference": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
          }
        }
      ]
    },
    "OriginatorCustomerParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/CustomerPartyType"
    },
    "BeneficiaryParty": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
          }
        }
      ]
    },
    "SellerSupplierParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/SupplierPartyType"
    },
    "BuyerCustomerParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/CustomerPartyType"
    },
    "Delivery": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DeliveryType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DeliveryType"
          }
        }
      ]
    },
    "DeliveryTerms": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DeliveryTermsType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DeliveryTermsType"
          }
        }
      ]
    },
    "DestinationCountry": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/CountryType"
    },
    "Contract": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/ContractType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/ContractType"
          }
        }
      ]
    },
    "RequestForQuotationLine": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/RequestForQuotationLineType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/RequestForQuotationLineType"
          },
          "minItems": 1
        }
      ]
    }
  },
  "required": [
    "$jsonschema",
    "IssueDate",
    "IssueTime",
    "SellerSupplierParty",
    "RequestForQuotationLine"
  ],
  "additionalProperties": false,
  "minProperties": 1,
  "title": "Request For Quotation. Details"
}

=== kduvekot/ubl-json/zWMqu/json/examples/UBL-RequestForQuotation-2.1-Example.json
{
  "$jsonschema": "urn:oasis:names:specification:ubl:schema:json:RequestForQuotation-2",
  "UBLVersionID": "2.1",
  "CustomizationID": "OIOUBL-2.1",
  "ProfileID": {
    "value": "Procurement-QuoSim-1.0",
    "schemeID": "urn:oioubl:id:profileid-1.2",
    "schemeAgencyID": "320"
  },
  "ID": "G867B",
  "CopyIndicator": false,
  "UUID": "93T5G3G5-HYA3-7267-BVG3-GS46SW44WG53",
  "IssueDate": "2008-04-19",
  "IssueTime": "11:32:26.0Z",
  "SubmissionDueDate": "2008-04-24",
  "Note": "Bestilling af computere",
  "PricingCurrencyCode": "DKK",
  "OriginatorCustomerParty": {
    "Party": {
      "EndpointID": {
        "value": "5798000416604",
        "schemeID": "GLN",
        "schemeAgencyID": "9"
      },
      "PartyIdentification": {
        "ID": {
          "value": "5798000416604",
          "schemeID": "GLN",
          "schemeAgencyID": "9"
        }
      },
      "PartyName": {
        "Name": "Gentofte Kommune"
      },
      "PostalAddress": {
        "AddressFormatCode": {
          "value": "StructuredDK",
          "listID": "urn:oioubl:codelist:addressformatcode-1.1",
          "listAgencyID": "320"
        },
        "StreetName": "Bernstorffsvej",
        "BuildingNumber": "161",
        "CityName": "Charlottenlund",
        "PostalZone": "2920",
        "Country": {
          "IdentificationCode": "DK"
        }
      },
      "PartyTaxScheme": {
        "CompanyID": {
          "value": "DK12345678",
          "schemeID": "DK:SE"
        },
        "TaxScheme": {
          "ID": {
            "value": "63",
            "schemeID": "urn:oioubl:id:taxschemeid-1.1",
            "schemeAgencyID": "320"
          },
          "Name": "Moms"
        }
      },
      "PartyLegalEntity": {
        "RegistrationName": "Gentofte Kommune",
        "CompanyID": {
          "value": "DK12345678",
          "schemeID": "DK:CVR"
        }
      },
      "Contact": {
        "ID": "12345678",
        "Name": "Sille Schyberg"
      }
    }
  },
  "SellerSupplierParty": {
    "CustomerAssignedAccountID": "LEV00123",
    "Party": {
      "EndpointID": {
        "value": "DK18296799",
        "schemeID": "DK:CVR"
      },
      "PartyIdentification": {
        "ID": {
          "value": "DK18296799",
          "schemeID": "DK:CVR"
        }
      },
      "PartyName": {
        "Name": "Delcomputer A/S"
      },
      "PostalAddress": {
        "AddressFormatCode": {
          "value": "StructuredDK",
          "listID": "urn:oioubl:codelist:addressformatcode-1.1",
          "listAgencyID": "320"
        },
        "StreetName": "Arne Jacobsens Allé",
        "BuildingNumber": "15",
        "CityName": "København S",
        "PostalZone": "2300",
        "Country": {
          "IdentificationCode": "DK"
        }
      },
      "PartyTaxScheme": {
        "CompanyID": {
          "value": "DK18296799",
          "schemeID": "DK:SE"
        },
        "TaxScheme": {
          "ID": {
            "value": "63",
            "schemeID": "urn:oioubl:id:taxschemeid-1.1",
            "schemeAgencyID": "320"
          },
          "Name": "Moms"
        }
      },
      "PartyLegalEntity": {
        "RegistrationName": "Delcomputer A/S",
        "CompanyID": {
          "value": "DK18296799",
          "schemeID": "DK:CVR"
        }
      }
    }
  },
  "Delivery": {
    "DeliveryAddress": {
      "AddressFormatCode": {
        "value": "StructuredDK",
        "listID": "urn:oioubl:codelist:addressformatcode-1.1",
        "listAgencyID": "320"
      },
      "StreetName": "Bernstorffsvej",
      "BuildingNumber": "161",
      "CityName": "Charlottenlund",
      "PostalZone": "2920",
      "AddressLine": [
        {
          "Line": "1. sal"
        },
        {
          "Line": "IT-afdelingen"
        }
      ],
      "Country": {
        "IdentificationCode": "DK"
      }
    },
    "RequestedDeliveryPeriod": {
      "StartDate": "2008-05-06",
      "StartTime": "09:30:47.0Z",
      "EndDate": "2008-05-10",
      "EndTime": "09:30:47.0Z"
    }
  },
  "DeliveryTerms": {
    "SpecialTerms": "1% reduktion i kontraktsummen pr. dags forsinkelse jf. SKI kontrakt"
  },
  "Contract": {
    "ContractDocumentReference": {
      "ID": "SKI123456",
      "IssueDate": "2006-01-01"
    }
  },
  "RequestForQuotationLine": [
    {
      "ID": "1",
      "Note": "Computer",
      "LineItem": {
        "ID": "DELL1052665",
        "Quantity": {
          "value": 35,
          "unitCode": "NIU"
        },
        "Item": {
          "Description": "Stationær computer",
          "Name": "Dell PrecisionTM  T3400"
        }
      }
    },
    {
      "ID": "2",
      "Note": "Skærm",
      "LineItem": {
        "ID": "DELL2363463",
        "Quantity": {
          "value": 35,
          "unitCode": "NIU"
        },
        "Item": {
          "Description": "Fladskærm",
          "Name": "FP/BL 1908WFP"
        }
      }
    },
    {
      "ID": "3",
      "Note": "Mus",
      "LineItem": {
        "ID": "DELL2367452",
        "Quantity": {
          "value": 35,
          "unitCode": "NIU"
        },
        "Item": {
          "Description": "Mus",
          "Name": "Dell Quietkey USB-tastatur, sort - Dansk (QWERTY)"
        }
      }
    },
    {
      "ID": "4",
      "Note": "Tastatur",
      "LineItem": {
        "ID": "DELL8436783",
        "Quantity": {
          "value": 35,
          "unitCode": "NIU"
        },
        "Item": {
          "Description": "Tastatur",
          "Name": "Dell Quietkey USB-tastatur, sort - Dansk (QWERTY)"
        }
      }
    }
  ]
}

=== kduvekot/ubl-json/zWMqu/json/examples/UBL-RequestForQuotation-2.0-Example.json
{
  "$jsonschema": "urn:oasis:names:specification:ubl:schema:json:RequestForQuotation-2",
  "UBLVersionID": "2.0",
  "CustomizationID": "urn:oasis:names:specification:ubl:xpath:RequestForQuotation-2.0:sbs-1.0-draft",
  "ProfileID": "bpid:urn:oasis:names:draft:bpss:ubl-2-sbs-request-for-quotation-draft",
  "ID": "G867B",
  "CopyIndicator": false,
  "UUID": "8D076867-AE6D-439F-8281-5AAFC7F4E3B1",
  "IssueDate": "2005-06-19",
  "IssueTime": "11:32:26.0Z",
  "Note": "sample",
  "CatalogueDocumentReference": {
    "ID": "2005-9A",
    "IssueDate": "2005-11-03"
  },
  "OriginatorCustomerParty": {
    "Party": {
      "PartyName": {
        "Name": "The Terminus"
      },
      "PostalAddress": {
        "StreetName": "Avon Way",
        "BuildingName": "Thereabouts",
        "BuildingNumber": "56A",
        "CityName": "Bridgtow",
        "PostalZone": "ZZ99 1ZZ",
        "CountrySubentity": "Avon",
        "AddressLine": {
          "Line": "3rd Floor, Room 5"
        },
        "Country": {
          "IdentificationCode": "GB"
        }
      },
      "PartyTaxScheme": {
        "RegistrationName": "Bridgtow District Council",
        "CompanyID": "12356478",
        "ExemptionReason": "Local Authority",
        "TaxScheme": {
          "ID": "UK VAT",
          "TaxTypeCode": "VAT"
        }
      },
      "Contact": {
        "Name": "S Massiah",
        "Telephone": "0127 98876545",
        "Telefax": "0127 98876546",
        "ElectronicMail": "smassiah@the-email.co.uk"
      }
    }
  },
  "SellerSupplierParty": {
    "CustomerAssignedAccountID": "CO001",
    "Party": {
      "PartyName": {
        "Name": "Consortial"
      },
      "PostalAddress": {
        "StreetName": "Busy Street",
        "BuildingName": "Thereabouts",
        "BuildingNumber": "56A",
        "CityName": "Farthing",
        "PostalZone": "AA99 1BB",
        "CountrySubentity": "Heremouthshire",
        "AddressLine": {
          "Line": "The Roundabout"
        },
        "Country": {
          "IdentificationCode": "GB"
        }
      },
      "PartyTaxScheme": {
        "RegistrationName": "Farthing Purchasing Consortium",
        "CompanyID": "175 269 2355",
        "ExemptionReason": "N/A",
        "TaxScheme": {
          "ID": "VAT",
          "TaxTypeCode": "VAT"
        }
      },
      "Contact": {
        "Name": "Mrs Bouquet",
        "Telephone": "0158 1233714",
        "Telefax": "0158 1233856",
        "ElectronicMail": "bouquet@fpconsortial.co.uk"
      }
    }
  },
  "Delivery": {
    "DeliveryAddress": {
      "StreetName": "Avon Way",
      "BuildingName": "Thereabouts",
      "BuildingNumber": "56A",
      "CityName": "Bridgtow",
      "PostalZone": "ZZ99 1ZZ",
      "CountrySubentity": "Avon",
      "AddressLine": {
        "Line": "3rd Floor, Room 5"
      },
      "Country": {
        "IdentificationCode": "GB"
      }
    },
    "RequestedDeliveryPeriod": {
      "StartDate": "2005-06-29",
      "StartTime": "09:30:47.0Z",
      "EndDate": "2005-06-29",
      "EndTime": "09:30:47.0Z"
    }
  },
  "DeliveryTerms": {
    "SpecialTerms": "1% deduction for late delivery as per contract"
  },
  "DestinationCountry": {
    "IdentificationCode": "GB",
    "Name": "Great Britain"
  },
  "Contract": {
    "ContractDocumentReference": {
      "ID": "GHJ76849",
      "IssueDate": "2002-08-13"
    }
  },
  "RequestForQuotationLine": {
    "ID": "1",
    "Note": "sample",
    "LineItem": {
      "ID": "1",
      "Quantity": {
        "value": 100,
        "unitCode": "KGM"
      },
      "Item": {
        "Description": "Acme beeswax",
        "Name": "beeswax",
        "BuyersItemIdentification": {
          "ID": "6578489"
        },
        "SellersItemIdentification": {
          "ID": "17589683"
        }
      }
    }
  }
}
